# -*- coding: utf-8 -*-
"""fatorial.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-u4-jpzo8JPh_lzW28_nEY8ZeFWBw8K3
"""

def Fatorial(num):
    produto = 1

    while(num > 0):
        produto = produto * num

        num = num - 1

    return produto